/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AgendaController;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Bruno Groehs
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;
    

    /**
     * Creates new form MenuPrincipal
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        
        iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        senha1 = new javax.swing.JLabel();
        senha2 = new javax.swing.JLabel();
        senha3 = new javax.swing.JLabel();
        senha4 = new javax.swing.JLabel();
        senha5 = new javax.swing.JLabel();
        senha6 = new javax.swing.JLabel();
        jTextObservacao = new javax.swing.JTextField();
        jTextHora = new javax.swing.JTextField();
        jTextCampoValor = new javax.swing.JTextField();
        jTextData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        JBoxClientes = new javax.swing.JComboBox<>();
        JBoxServicos = new javax.swing.JComboBox<>();
        jButtonCriaCliente = new javax.swing.JButton();
        jButtonCriaClienteServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 84, 204));

        senha1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        senha1.setForeground(new java.awt.Color(255, 255, 255));
        senha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha1.setText("Cliente");
        senha1.setToolTipText("");
        senha1.setAlignmentY(0.0F);

        senha2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        senha2.setForeground(new java.awt.Color(255, 255, 255));
        senha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha2.setText("Servico");
        senha2.setToolTipText("");
        senha2.setAlignmentY(0.0F);

        senha3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        senha3.setForeground(new java.awt.Color(255, 255, 255));
        senha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha3.setText("Valor R$");
        senha3.setToolTipText("");
        senha3.setAlignmentY(0.0F);

        senha4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        senha4.setForeground(new java.awt.Color(255, 255, 255));
        senha4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha4.setText("Data");
        senha4.setToolTipText("");
        senha4.setAlignmentY(0.0F);

        senha5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        senha5.setForeground(new java.awt.Color(255, 255, 255));
        senha5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha5.setText("Observação");
        senha5.setToolTipText("");
        senha5.setAlignmentY(0.0F);

        senha6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        senha6.setForeground(new java.awt.Color(255, 255, 255));
        senha6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha6.setText("Hora");
        senha6.setToolTipText("");
        senha6.setAlignmentY(0.0F);

        jTextObservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextObservacaoActionPerformed(evt);
            }
        });

        jTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHoraActionPerformed(evt);
            }
        });
        jTextHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextHoraKeyTyped(evt);
            }
        });

        jTextCampoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCampoValorActionPerformed(evt);
            }
        });

        jTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataActionPerformed(evt);
            }
        });
        jTextData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDataKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observacao"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setText("AGENDAR SERVIÇO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBoxClientesActionPerformed(evt);
            }
        });

        JBoxServicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JBoxServicosItemStateChanged(evt);
            }
        });
        JBoxServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBoxServicosActionPerformed(evt);
            }
        });

        jButtonCriaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N
        jButtonCriaCliente.setToolTipText("");
        jButtonCriaCliente.setBorder(null);
        jButtonCriaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriaClienteActionPerformed(evt);
            }
        });

        jButtonCriaClienteServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N
        jButtonCriaClienteServico.setToolTipText("");
        jButtonCriaClienteServico.setBorder(null);
        jButtonCriaClienteServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriaClienteServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(senha2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(senha4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(senha3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(senha6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(senha5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextObservacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCampoValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBoxServicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCriaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCriaClienteServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(41, 41, 41))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBoxClientes, JBoxServicos, jTextCampoValor, jTextData, jTextHora, jTextObservacao});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {senha1, senha2, senha3, senha4, senha5, senha6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCriaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(senha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JBoxServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(senha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCriaClienteServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senha3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jTextCampoValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senha4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senha6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senha5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(207, 207, 207))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JBoxClientes, JBoxServicos, jTextCampoValor, jTextData, jTextHora, jTextObservacao});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriaClienteServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriaClienteServicoActionPerformed
        controller.navegaParaCadastroServico();
    }//GEN-LAST:event_jButtonCriaClienteServicoActionPerformed

    private void jButtonCriaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriaClienteActionPerformed
        // TODO add your handling code here:
        controller.navegaParaCadastroCliente();
    }//GEN-LAST:event_jButtonCriaClienteActionPerformed

    private void JBoxServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBoxServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBoxServicosActionPerformed

    private void JBoxServicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JBoxServicosItemStateChanged
        this.controller.atualizaValor();
    }//GEN-LAST:event_JBoxServicosItemStateChanged

    private void JBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBoxClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBoxClientesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.agendar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextCampoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCampoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCampoValorActionPerformed

    private void jTextObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextObservacaoActionPerformed
    /*Fazendo com que a data fique no formato certo sem precisar inserir (/)*/
    private void jTextDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDataKeyTyped
        String caracteresPermitidos = "0123456789/";
    if(!caracteresPermitidos.contains(evt.getKeyChar() + "")){
        evt.consume();
    }
    if(jTextData.getText().length() >= 10 && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE){
        evt.consume();
    }
    
    switch(jTextData.getText().length()){
        case 2:
            if (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE)
                jTextData.setText(jTextData.getText() + "/");
            break;
        case 5:
            if (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE)
            jTextData.setText(jTextData.getText() + "/");
            break;
    }
    }//GEN-LAST:event_jTextDataKeyTyped

    private void jTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataActionPerformed

    private void jTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHoraActionPerformed

    private void jTextHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHoraKeyTyped
        // TODO add your handling code here:
        String caracteresPermitidos = "0123456789:";
    if(!caracteresPermitidos.contains(evt.getKeyChar() + "")){
        evt.consume();
    }
    if(jTextHora.getText().length() >= 5 && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE){
        evt.consume();
    }
    
    switch(jTextHora.getText().length()){
        case 2:
            if (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE)
                jTextHora.setText(jTextHora.getText() + ":");
            break;
    }
    }//GEN-LAST:event_jTextHoraKeyTyped
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JBoxClientes;
    private javax.swing.JComboBox<String> JBoxServicos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCriaCliente;
    private javax.swing.JButton jButtonCriaClienteServico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCampoValor;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextObservacao;
    private javax.swing.JLabel senha1;
    private javax.swing.JLabel senha2;
    private javax.swing.JLabel senha3;
    private javax.swing.JLabel senha4;
    private javax.swing.JLabel senha5;
    private javax.swing.JLabel senha6;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JComboBox<String> getJBoxClientes() {
        return JBoxClientes;
    }

    public void setJBoxClientes(JComboBox<String> JBoxClientes) {
        this.JBoxClientes = JBoxClientes;
    }

    public JComboBox<String> getJBoxServicos() {
        return JBoxServicos;
    }

    public void setJBoxServicos(JComboBox<String> JBoxServicos) {
        this.JBoxServicos = JBoxServicos;
    }

    public JTextField getJTextCampoValor() {
        return jTextCampoValor;
    }

    public void setJTextCampoValor(JTextField jTextCampoValor) {
        this.jTextCampoValor = jTextCampoValor;
    }

    public JTextField getjTextData() {
        return jTextData;
    }

    public void setjTextData(JTextField jTextData) {
        this.jTextData = jTextData;
    }

    public JTextField getjTextHora() {
        return jTextHora;
    }

    public void setjTextHora(JTextField jTextHora) {
        this.jTextHora = jTextHora;
    }

    public JTextField getjTextObservacao() {
        return jTextObservacao;
    }

    public void setjTextObservacao(JTextField jTextObservacao) {
        this.jTextObservacao = jTextObservacao;
    }

    public JTextField getjTextCampoValor() {
        return jTextCampoValor;
    }

    public void setjTextCampoValor(JTextField jTextCampoValor) {
        this.jTextCampoValor = jTextCampoValor;
    }
    
}
