/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bruno Groehs
 */
public class CadastroCliente extends javax.swing.JFrame {
    private final ClienteController clienteController;
    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        this.clienteController = new ClienteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNomeCadastroCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTelefoneCadastroCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jEmailCadastroCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNomeCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeCadastroClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jNomeCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, 40));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 110, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 40));

        jTelefoneCadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTelefoneCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefoneCadastroClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTelefoneCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, 40));

        jEmailCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailCadastroClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jEmailCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FundoLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 320, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeCadastroClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clienteController.criaCliente();
        setVisible(false);
        Agenda agenda = new Agenda();
        agenda.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTelefoneCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefoneCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelefoneCadastroClienteActionPerformed

    private void jEmailCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailCadastroClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public JTextField getjEmailCadastroCliente() {
        return jEmailCadastroCliente;
    }

    public void setjEmailCadastroCliente(JTextField jEmailCadastroCliente) {
        this.jEmailCadastroCliente = jEmailCadastroCliente;
    }

    public JTextField getjNomeCadastroCliente() {
        return jNomeCadastroCliente;
    }

    public void setjNomeCadastroCliente(JTextField jNomeCadastroCliente) {
        this.jNomeCadastroCliente = jNomeCadastroCliente;
    }

    public JTextField getjTelefoneCadastroCliente() {
        return jTelefoneCadastroCliente;
    }

    public void setjTelefoneCadastroCliente(JTextField jTelefoneCadastroCliente) {
        this.jTelefoneCadastroCliente = jTelefoneCadastroCliente;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jEmailCadastroCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNomeCadastroCliente;
    private javax.swing.JTextField jTelefoneCadastroCliente;
    // End of variables declaration//GEN-END:variables
}
