/* m
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuPrincipalController;
import javax.swing.JTable;


/**
 *
 * @author Bruno Groehs
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        controller = new MenuPrincipalController(this);
        initComponents();
        incia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientesHoje = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCriaCliente = new javax.swing.JMenuItem();
        jMenuCriaServico = new javax.swing.JMenuItem();
        jMenuAddUsuario = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        menuAgenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableClientesHoje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Horario", "Servico", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTableClientesHoje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 47, -1, 410));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES HOJE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/6867640.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 723, 477));

        jMenuCadastro.setText("Cadastro");

        jMenuCriaCliente.setText("Cria Cliente");
        jMenuCriaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCriaClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCriaCliente);

        jMenuCriaServico.setText("Cria Servico");
        jMenuCriaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCriaServicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCriaServico);

        jMenuAddUsuario.setText("Adciona Usuario");
        jMenuAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuAddUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacao.setText("Operação");

        menuAgenda.setText("Agenda");
        menuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendaActionPerformed(evt);
            }
        });
        jMenuOperacao.add(menuAgenda);

        jMenuBar1.add(jMenuOperacao);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCriaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCriaClienteActionPerformed
        this.controller.navegarParaCriaCliente();
    }//GEN-LAST:event_jMenuCriaClienteActionPerformed

    private void menuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendaActionPerformed
        this.controller.navegarParaAgenda();
        setVisible(false);
    }//GEN-LAST:event_menuAgendaActionPerformed

    private void jMenuCriaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCriaServicoActionPerformed
        this.controller.navegarParaCriaServico();
    }//GEN-LAST:event_jMenuCriaServicoActionPerformed

    private void jMenuAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddUsuarioActionPerformed
        this.controller.navegarParaAddUsuario();
    }//GEN-LAST:event_jMenuAddUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuAddUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCriaCliente;
    private javax.swing.JMenuItem jMenuCriaServico;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientesHoje;
    private javax.swing.JMenuItem menuAgenda;
    // End of variables declaration//GEN-END:variables
    
    private void incia() {
        controller.atualizaTabelaClienteHoje();
    }

    public JTable getjTableClientesHoje() {
        return jTableClientesHoje;
    }

    public void setjTableClientesHoje(JTable jTableClientesHoje) {
        this.jTableClientesHoje = jTableClientesHoje;
    }
    
}
